name = "rizzo"
version = "0.1.0"
defaultTargets = ["Rizzo", "Examples"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "Rizzo"

[[lean_lib]]
name = "Examples"